<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DualSenseClient.Tests"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ppy.SDL3-CS" Version="2026.722.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DualSenseClient.Logging\DualSenseClient.Logging.csproj" />
    </ItemGroup>

</Project>
