<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Tmds.DBus" Version="0.95.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DualSenseClient.Logging\DualSenseClient.Logging.csproj" />
    </ItemGroup>

</Project>
